let Images = {
  IcSms: require('../assets/images/IcSms.png'),
  IcPhone: require('../assets/images/IcPhone.png'),
  IcMessages: require('../assets/images/IcMessages.png'),
  IcLogo: require('../assets/images/IcLogo.png'),
  IcProfile: require('../assets/images/IcProfile.png'),
  IcAdd: require('../assets/images/IcAdd.png'),
  IcConfirmPassword: require('../assets/images/IcConfirmPassword.png'),
  IcProfilePic: require('../assets/images/IcProfilePic.png'),
  IcAddress: require('../assets/images/IcAddress.png'),
  IcCake: require('../assets/images/IcCake.png'),
  IcPassword: require('../assets/images/IcPassword.png'),
  IcPhoneNo: require('../assets/images/IcPhoneNo.png'),
  IcDownArrow: require('../assets/images/IcDownArrow.png'),
  IcLeftArrow: require('../assets/images/IcLeftArrow.png'),
  IcOpenEye: require('../assets/images/icOpenEye.png'),
  IcCloseEye: require('../assets/images/IcCloseEye.png'),
  IcMap: require('../assets/images/IcMap.png'),
  IcGps: require('../assets/images/IcGps.png'),
  IcProfileCircle: require('../assets/images/IcProfileCircle.png'),
  IcHome: require('../assets/images/IcHome.png'),
  IcSettings: require('../assets/images/IcSettings.png'),
  IcHuman: require('../assets/images/IcHuman.png'),
  IcContact: require('../assets/images/IcContact.png'),
  IcAlert: require('../assets/images/IcDanger.png'),
  IcDelete: require('../assets/images/IcDelete.png'),
  IcEdit: require('../assets/images/IcEdit.png'),
  IcEmergency: require('../assets/images/IcEmergency.png'),
  IcLogout: require('../assets/images/IcLogout.png'),
  // IcSettings: require('../assets/images/IcSettings.png'),
};
export default Images;
